name = input("enter your name ")
school = input("enter your school name ")
age = input("enter your age ")
program = input("enter the program you are enrolled ")
hobbies = input("enter your hobbies ")
print("name "+name,school,age,program,hobbies,sep="\t\n")